### ISSUE TITLE
Create the User Profile Endpoint

### ISSUE THREAD

**Issue by kiikoh** [kiikoh/Rowlog-FE#2]
The request will have a parameter corresponding to the user id. Additionally, the leaderboard will also need to have a user id so that I can create links to an individual's profile page. 

The profile JSON should look like this

```
name: "",
            metersScored: "",
            side: "",
            year: "",
            boat: "",
            workouts: [
                {
                    date: "",
                    type: "",
                    heartrate: 0,
                    meters: "",
                    split: "",
                    comment: ""
                }
            ]
```

**Comment by rmdmattingly** [comment]
I'm also going to put together an endpoint that takes in a `wid` (workout id) parameter on a DELETE request so that we can support deletion of workouts.  Down the road it'd be _nice_ to support editing of previously submitted workouts, but I don't think it's imperative while we offer deletion.  

I think editing workouts also opens up some possibility for lowering data integrity.  Makes the system less real time, especially if we allow people to edit workout time.

**Comment by rmdmattingly** [comment]
https://rows.tech/api/profile/?people_id=84
